[env:t-watch-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_T_WATCH_S3
    -DLV_CONF_INCLUDE_SIMPLE
    -Isrc/

lib_deps =
    lewisxhe/XPowersLib @ ^0.2.7
    bblanchon/ArduinoJson @ ^7.0.4
    https://github.com/Xinyuan-LilyGO/LilyGoLib
    lvgl/lvgl @ ^8.3.11

