[env:t-watch-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_T_WATCH_S3
    -DLV_CONF_INCLUDE_SIMPLE
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -Isrc/
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DUSING_AXP2101

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    lvgl/lvgl @ 8.3.11
    lewisxhe/XPowersLib @ 0.2.9
    lewisxhe/SensorLib @ 0.3.1
    bodmer/TFT_eSPI @ 2.5.43
    arduino-libraries/NTPClient @ ^3.2.1
    densaugeo/base64 @ ^1.4.0
    mikalhart/TinyGPSPlus @ ^1.0.3

board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
